module.exports = Object.freeze
({
    RECEPTIONVISIT: "RECEPTIONVISIT",
    FOODCOURTVISIT: "FOODCOURTVISIT",
    BASICTUTORIALCLICK: "BASICTUTORIALCLICK", //done
    RECEPTIONVISIT: "RECEPTIONVISIT",
    FOYERVISIT: "FOYERVISIT",
    LECTUREVISIT: "LECTUREVISIT",
    BEFRIENDOTHER: "BEFRIENDOTHER", //done
    INITPERSONALCHAT: "INITPERSONALCHAT",
    ASKQUESTIONINLECTURE: "ASKQUESTIONINLECTURE" //done
});
