module.exports = Object.freeze
({
    RECEPTIONVISIT: "RECEPTIONVISIT", //done
    FOODCOURTVISIT: "FOODCOURTVISIT", //done
    BASICTUTORIALCLICK: "BASICTUTORIALCLICK", //done
    FOYERHELPERCLICK: "FOYERHELPERCLICK", //done
    CHEFCLICK: "CHEFCLICK", //done
    RECEPTIONVISIT: "RECEPTIONVISIT", //done
    FOYERVISIT: "FOYERVISIT", //done
    LECTUREVISIT: "LECTUREVISIT", //done
    BEFRIENDOTHER: "BEFRIENDOTHER", //done
    INITPERSONALCHAT: "INITPERSONALCHAT", //done
    ASKQUESTIONINLECTURE: "ASKQUESTIONINLECTURE" //done
});
