module.exports = Object.freeze({
    RECEPTIONVISIT: "RECEPTIONVISIT",
    FOODCOURTVISIT: "FOODCOURTVISIT",
    BASICTUTORIALCLICK: "BASICTUTORIALCLICK",
    FOYERHELPERCLICK: "FOYERHELPERCLICK",
    CHEFCLICK: "CHEFCLICK",
    FOYERVISIT: "FOYERVISIT",
    LECTUREVISIT: "LECTUREVISIT",
    BEFRIENDOTHER: "BEFRIENDOTHER",
    INITPERSONALCHAT: "INITPERSONALCHAT",
    ASKQUESTIONINLECTURE: "ASKQUESTIONINLECTURE",
    SENDALLCHAT: "SENDALLCHAT" //for test purposes, not really used.
});
